"""
Chat endpoint as a Flask Blueprint.
Fully migrated to persistent PostgreSQL storage.
"""

import time
import uuid
import re
from datetime import datetime, timezone
import os
from flask import Blueprint, request, jsonify
from models import db, Conversation, Message
from sqlalchemy.orm.attributes import flag_modified

from models import ExtractedEntities, ClassifiedResult
from app_config import (
    ORDER_INTENTS,
    ORDER_CREATE_INTENTS,
    CLASSIFIER_PROVIDER_TAG,
    get_currency_symbol,
)
from woo_client import woo_client
from formatters import format_product, format_custom_product, format_category, _entities_to_dict
from response_generator import generate_bot_message, generate_suggestions, _resolve_user_placeholders
from models import Intent, WooAPICall
from classifier import classify
from api_builder import build_api_calls
from conversation_flow import FlowState, handle_flow_state
from chat_logger import get_logger, sanitize_log_string
from store_registry import get_store_loader

from handlers.chat_utils import default_pagination, build_pagination, format_order_for_frontend
from handlers.flow_handler import handle_flow
from handlers.llm_handler import run_llm_fallback
from handlers.order_handler import handle_reorder, handle_order_detail, handle_quick_order, handle_historical_search
from handlers.variant_handler import handle_variant_selection, handle_variation_product, handle_quantity_and_variant_check
from handlers.search_handler import log_matched_products, handle_empty_results
from utils.language_utils import detect_and_translate

logger = get_logger("miraq_chat")
chat_bp = Blueprint("chat", __name__)


# ══════════════════════════════════════════════════════════════
# ─── DATABASE SESSION HELPERS ───
# ══════════════════════════════════════════════════════════════

def resolve_session_id():
    """Resolves the chat session ID from X-MiraQ-Session header or generates a new one."""
    miraq_session = request.headers.get('X-MiraQ-Session')
    if miraq_session:
        try:
            return uuid.UUID(miraq_session)
        except ValueError:
            logger.warning(f"Invalid X-MiraQ-Session format received: {miraq_session}")
    return uuid.uuid4()


def _finalize_turn(conversation, flask_response):
    """
    Interceptor: Extracts bot message from Flask response, saves to DB, 
    commits the transaction, and returns the updated response.
    """
    if isinstance(flask_response, tuple):
        resp_obj, status_code = flask_response
    else:
        resp_obj, status_code = flask_response, 200
        
    try:
        data = resp_obj.get_json()
    except Exception:
        data = {}
        
    if not data:
        db.session.commit()
        return flask_response
        
    # 1. Save Bot Message
    bot_msg = Message(
        conversation_id=conversation.id,
        role="bot",
        content=data.get("bot_message", ""),
        intent=data.get("intent", ""),
        metadata_json=data.get("metadata", {})
    )
    db.session.add(bot_msg)
    
    # 2. Update Conversation State
    conversation.flow_state = data.get("flow_state", conversation.flow_state)
    
    # Extract detached context
    context_data = dict(conversation.context_data)
    
    # Wipe context variables when outgoing state resets
    if conversation.flow_state in ("idle", "awaiting_anything_else", "closing"):
        keys_to_wipe = [
            "pending_product_id", "pending_product_name", 
            "pending_quantity", "pending_variation_id", "resolved_attributes",
            "pending_shipping_address", "use_existing_address", "use_new_address"
        ]
        for k in keys_to_wipe:
            context_data.pop(k, None)
            
        if "metadata" in data:
            for k in keys_to_wipe:
                data["metadata"].pop(k, None)
    else:
        # save any flow variables generated by handlers to the DB!
        if "metadata" in data:
            sync_keys = [
                "pending_product_id", "pending_product_name", "pending_quantity", 
                "pending_variation_id", "pending_shipping_address", 
                "use_existing_address", "use_new_address", "resolved_attributes"
            ]
            for k in sync_keys:
                if k in data["metadata"] and data["metadata"][k] is not None:
                    context_data[k] = data["metadata"][k]

    # Force new object reference for SQLAlchemy JSONB mutation tracking
    conversation.context_data = context_data
    flag_modified(conversation, "context_data")
    
    # 3. Commit Transaction
    db.session.commit()
    
    # 4. Inject explicit UUID into payload for frontend
    data["session_id"] = str(conversation.id)
    return jsonify(data), status_code

# ══════════════════════════════════════════════════════════════
# ─── HISTORY ROUTE ───
# ══════════════════════════════════════════════════════════════

@chat_bp.route('/chat/history', methods=['GET'])
def get_chat_history():
    """Fetches paginated chat history for the frontend to hydrate the UI."""
    miraq_session = request.headers.get('X-MiraQ-Session')
    if not miraq_session:
        return jsonify({"messages": [], "has_more": False}), 200

    try:
        session_uuid = uuid.UUID(miraq_session)
        conversation = Conversation.query.get(session_uuid)
        
        if not conversation:
            return jsonify({"messages": [], "has_more": False}), 200

        # Pagination parameters
        page = int(request.args.get('page', 1))
        limit = int(request.args.get('limit', 20)) # Load 20 messages at a time
        offset = (page - 1) * limit

        # Fetch messages descending (newest first) so page 1 is the most recent
        messages_query = Message.query.filter_by(conversation_id=session_uuid)\
            .order_by(Message.created_at.desc())\
            .limit(limit).offset(offset).all()

        # Count total to determine if there's more history
        total_messages = Message.query.filter_by(conversation_id=session_uuid).count()
        has_more = (offset + limit) < total_messages

        # Reverse the chunk so they display in chronological order (top to bottom)
        messages_query.reverse()

        history = []
        for msg in messages_query:
            history.append({
                "role": msg.role,
                "message": msg.content,
                "intent": msg.intent,
                "timestamp": msg.created_at.isoformat()
            })

        return jsonify({
            "messages": history, 
            "has_more": has_more, 
            "next_page": page + 1 if has_more else None
        }), 200

    except ValueError:
        return jsonify({"messages": [], "has_more": False}), 200

# ══════════════════════════════════════════════════════════════
# ─── PARSER ───
# ══════════════════════════════════════════════════════════════

def parse_csv_message(msg: str, loader) -> ClassifiedResult | None:
    """Hybrid Parser: Uses Longest-String Substring Matching on natural language."""
    
    msg_lower = msg.lower()
    entities = ExtractedEntities()
    if not hasattr(entities, 'target_category_slugs'):
        entities.target_category_slugs = set()
        
    # Run baseline classification exactly once at the top
    original_nlp_result = classify(msg)
        
    if not loader:
        return original_nlp_result

    # ─── PHASE 1: LONGEST-STRING EXACT MATCH ───
    # Fetch the pre-sorted catalog from memory in O(1) time
    catalog_items = getattr(loader, 'longest_match_catalog', [])

    # Group items by identical string (Python dicts preserve the length-sorted order automatically)
    grouped_catalog = {}
    for name, match_type, data in catalog_items:
        if name not in grouped_catalog:
            grouped_catalog[name] = []
        grouped_catalog[name].append((match_type, data))

    unmatched_text = msg_lower
    
    for name, matches in grouped_catalog.items():
        if len(name) < 3:
            continue
            
        # Make Phase 1 plural/singular tolerant safely
        # Normalize hyphens → spaces so "black-look" slug matches "black look" in text
        normalized_name = name.replace('-', ' ')
        parts = []
        for w in normalized_name.split():
            if w.endswith('s') and not w.endswith('ss') and len(w) > 3:
                parts.append(rf'{re.escape(w[:-1])}s?')
            else:
                parts.append(re.escape(w))
        flexible_name = r'\s+'.join(parts)
        
        # Use negative lookarounds instead of \b to support quotes/punctuation
        pattern = r'(?<!\w)(' + flexible_name + r')(?!\w)'
        
        if re.search(pattern, unmatched_text):
            # Check if this exact string yielded BOTH a Tag and an Attribute
            types_matched = [m[0] for m in matches]
            is_collision = 'tag' in types_matched and 'attribute' in types_matched
            
            if is_collision:
                tag_data = next(m[1] for m in matches if m[0] == 'tag')
                attr_data = next(m[1] for m in matches if m[0] == 'attribute')
                
                # Pass both to the API builder as a tied pair!
                if not hasattr(entities, 'attr_tag_or_pairs'):
                    entities.attr_tag_or_pairs = []
                    
                entities.attr_tag_or_pairs.append({
                    "tag_slug":      tag_data.get("slug"),
                    "attr_taxonomy": attr_data.get("label", ""),  # label e.g. "finish" -> resolved to "pa_finish" by api_builder
                    "attr_term":     attr_data.get("slug"),       # term slug e.g. "7-16", "matte"
                    "display_text":  name                         # original matched text for bot message
                })
                
            else:
                # Standard assignment for single matches
                for match_type, data in matches:
                    if match_type == 'tag':
                        entities.tag_slugs.append(data.get("slug"))
                        entities.tag_ids.append(data.get("id"))
                    elif match_type == 'product':
                        if not entities.product_id:
                            entities.product_name = data.get("name")
                            entities.product_slug = data.get("slug", "")
                            entities.product_id = data.get("id")
                    elif match_type == 'category':
                        # Retrieve ALL slugs that share this category name
                        name_lower = data.get("name", "").lower()
                        all_slugs = getattr(loader, 'category_slugs_by_name', {}).get(name_lower, [data.get("slug")])
                        entities.target_category_slugs.update(all_slugs)
                        
                        cat_name = data.get("name") or ""
                        if not getattr(entities, 'category_name', None):
                            entities.category_name = cat_name
                        elif cat_name and cat_name not in entities.category_name:
                            existing = [n.strip() for n in re.split(r',\s*|\s*&\s*', entities.category_name) if n.strip()]
                            existing.append(cat_name)
                            entities.category_name = ", ".join(existing[:-1]) + " & " + existing[-1] if len(existing) > 1 else existing[0]
                    elif match_type == 'attribute':
                        label = data['label']
                        term_slug = data['slug']
                        if label not in entities.attributes:
                            entities.attributes[label] = term_slug
                        else:
                            entities.attributes[label] += f",{term_slug}"
            
            # Remove the matched phrase from the string ONCE for all matches
            unmatched_text = re.sub(pattern, " ", unmatched_text)

    # ─── PHASE 2: REGEX NLP FALLBACK ───
    # Pass the UNMATCHED text to the classifier to get numerical entities and leftovers
    nlp_result = classify(unmatched_text)
    nlp_entities = nlp_result.entities
    
    # Purge zero-count categories injected by classify()
    if loader and getattr(nlp_entities, 'target_category_slugs', None):
        alive_slugs = {
            s for s in nlp_entities.target_category_slugs
            if loader.category_by_slug.get(s, {}).get("count", 0) > 0
        }
        nlp_entities.target_category_slugs = alive_slugs
        if not alive_slugs:
            nlp_entities.category_name = None
    
    # Merge Positive Entities
    if getattr(nlp_entities, 'product_id', None) and not getattr(entities, 'product_id', None):
        entities.product_name = nlp_entities.product_name
        entities.product_slug = nlp_entities.product_slug
        entities.product_id = nlp_entities.product_id
        
    if getattr(nlp_entities, 'target_category_slugs', None):
        entities.target_category_slugs.update(nlp_entities.target_category_slugs)
        nlp_cat_name = getattr(nlp_entities, 'category_name', None) or ""
        if nlp_cat_name:
            if not getattr(entities, 'category_name', None):
                entities.category_name = nlp_cat_name
            elif nlp_cat_name not in entities.category_name:
                existing = [n.strip() for n in re.split(r',\s*|\s*&\s*', entities.category_name) if n.strip()]
                existing.append(nlp_cat_name)
                entities.category_name = ", ".join(existing[:-1]) + " & " + existing[-1] if len(existing) > 1 else existing[0]
            
    if getattr(nlp_entities, 'tag_ids', None):
        for tid, tslug in zip(nlp_entities.tag_ids, nlp_entities.tag_slugs):
            if tid not in entities.tag_ids:
                entities.tag_ids.append(tid)
                entities.tag_slugs.append(tslug)
                
    if getattr(nlp_entities, 'attributes', None):
        for k, v in nlp_entities.attributes.items():
            if k not in entities.attributes:
                entities.attributes[k] = v
            else:
                existing_vals = entities.attributes[k].split(",")
                new_vals = [val for val in v.split(",") if val not in existing_vals]
                if new_vals:
                    entities.attributes[k] += "," + ",".join(new_vals)
    
    # Merge Exclusions & Numerical Values
    
    if getattr(original_nlp_result.entities, 'target_attribute', None):
        entities.target_attribute = original_nlp_result.entities.target_attribute
        
    if getattr(original_nlp_result.entities, 'target_attributes', None):
        if not hasattr(entities, 'target_attributes'): 
            entities.target_attributes = []
        for t_attr in original_nlp_result.entities.target_attributes:
            if t_attr not in entities.target_attributes:
                entities.target_attributes.append(t_attr)

    if getattr(nlp_entities, 'excluded_tags', None):
        if not hasattr(entities, 'excluded_tags'): entities.excluded_tags = []
        entities.excluded_tags.extend(nlp_entities.excluded_tags)
        
    if getattr(nlp_entities, 'excluded_categories', None):
        if not hasattr(entities, 'excluded_categories'): entities.excluded_categories = []
        entities.excluded_categories.extend(nlp_entities.excluded_categories)
        
    if getattr(nlp_entities, 'excluded_attributes', None):
        if not hasattr(entities, 'excluded_attributes'): entities.excluded_attributes = {}
        for k, v in nlp_entities.excluded_attributes.items():
            if k not in entities.excluded_attributes: entities.excluded_attributes[k] = v
            else: entities.excluded_attributes[k].extend(v)
            
    if getattr(nlp_entities, 'excluded_search_term', None):
        entities.excluded_search_term = nlp_entities.excluded_search_term
        
    if getattr(nlp_entities, 'in_stock', None) is not None: entities.in_stock = nlp_entities.in_stock
    if getattr(nlp_entities, 'on_sale', None) is not None: entities.on_sale = nlp_entities.on_sale
    if getattr(nlp_entities, 'min_price', None) is not None: entities.min_price = nlp_entities.min_price
    if getattr(nlp_entities, 'max_price', None) is not None: entities.max_price = nlp_entities.max_price
    if getattr(nlp_entities, 'collection_year', None) is not None: entities.collection_year = nlp_entities.collection_year
    if getattr(nlp_entities, 'date_after', None) is not None: entities.date_after = nlp_entities.date_after
    if getattr(nlp_entities, 'date_before', None) is not None: entities.date_before = nlp_entities.date_before
    if getattr(nlp_entities, 'order_count', None) is not None: entities.order_count = nlp_entities.order_count
    
    _action_fields = [
        'quantity', 'order_id', 'reorder', 'explicit_last_order', 'order_item_name', 
        'quick_ship', 'customer_updates', 'billing_updates', 'shipping_updates', 
        'customer_fields_requested'
    ]
    for _f in _action_fields:
        _val = getattr(original_nlp_result.entities, _f, None)
        if _val is not None and _val != [] and _val != {}:
            setattr(entities, _f, _val)
    
    if nlp_entities.semantic_matches:
        entities.semantic_matches.extend(nlp_entities.semantic_matches)
        
    if getattr(original_nlp_result.entities, 'attr_tag_or_pairs', None):
        if not hasattr(entities, 'attr_tag_or_pairs'):
            entities.attr_tag_or_pairs = []

        for pair in original_nlp_result.entities.attr_tag_or_pairs:
            if pair not in entities.attr_tag_or_pairs:
                entities.attr_tag_or_pairs.append(pair)

            # ─── 1. Clean up redundant attributes ───
            attr_term = pair.get("attr_term", "")
            if attr_term and hasattr(entities, 'attributes'):
                keys_to_remove = []
                for k, v in entities.attributes.items():
                    vals = [x.strip() for x in v.split(",")]
                    if attr_term in vals:
                        vals.remove(attr_term)
                        if not vals:
                            keys_to_remove.append(k)
                        else:
                            entities.attributes[k] = ",".join(vals)
                            
                for k in keys_to_remove:
                    del entities.attributes[k]
            
            # ─── 2. Clean up redundant categories ───
            cat_slugs = pair.get("cat_slugs", [])
            if cat_slugs and hasattr(entities, 'target_category_slugs'):
                for c_slug in cat_slugs:
                    if c_slug in entities.target_category_slugs:
                        entities.target_category_slugs.remove(c_slug)
                
                # If removing the overlap leaves the category list empty, nullify the name
                if not entities.target_category_slugs:
                    entities.category_name = None
                                   

    # ─── PHASE 2.5 & 3: ADJECTIVE ISOLATION & SEMANTIC FALLBACK ───
    STOP_WORDS = {
        "a", "an", "the", "and", "or", "for", "to", "of", "in", "on", "at", "by", "with", "from",
        "is", "are", "am", "i", "i'm", "im", "my", "me", "you", "your", "it", "that", "this", "these", "those",
        "what", "how", "who", "where", "why", "which", "do", "does", "did", "can", "could", "would",
        "show", "tell", "give", "find", "search", "looking", "look", "suggest", "recommend", "want", "need",
        "product", "products", "item", "items", "option", "options", "something", "anything", "some", "any",
        "series", "collection", "line", "brand", "style", "type", "have", "has", "had",
        "please", "thanks", "thank", "hello", "hi", "hey",
        "under", "over", "above", "below", "latest", "newest", "recent", "new", "top", "bottom"
    }
    
    def _clean_leftovers(text_chunk):
        if not text_chunk: return ""
        text_chunk = text_chunk.replace(",", " ")
        words = text_chunk.split()
        kept_words = []
        for w in words:
            clean_w = w.lower().strip('?,.!;:')
            if clean_w and clean_w not in STOP_WORDS:
                kept_words.append(clean_w)
        return " ".join(kept_words)

    # Preserve the strict WooCommerce search term (stripped of generic noise)
    strict_search_term = getattr(nlp_entities, 'search_term', None)
    
    # Give the Vector AI the full unstripped context!
    raw_pos_for_vectors = unmatched_text if unmatched_text else strict_search_term
    raw_neg = getattr(nlp_entities, 'excluded_search_term', None)

    # Clean the text FIRST to isolate meaningful adjectives
    cleaned_pos_text = _clean_leftovers(raw_pos_for_vectors)
    cleaned_neg_text = _clean_leftovers(raw_neg)

    still_unmatched_pos = []
    still_unmatched_neg = []

    if (cleaned_pos_text or cleaned_neg_text) and loader:
        import torch
        from sentence_transformers import util
        SEMANTIC_THRESHOLD = 0.55 
        
        if not hasattr(loader, 'semantic_tensors') or loader.semantic_tensors is None:
            if cleaned_pos_text: still_unmatched_pos.append(cleaned_pos_text)
            if cleaned_neg_text: still_unmatched_neg.append(cleaned_neg_text)
        else:
            def _process_vectors(term_string, is_negative=False):
                unmatched = []
                phrase = term_string.strip()
                if not phrase: return unmatched
                
                # Evaluate the WHOLE phrase first to preserve semantic context!
                user_vector = loader.vector_model.encode(phrase, convert_to_tensor=True)
                cosine_scores = util.cos_sim(user_vector, loader.semantic_tensors)[0]
                top_results = torch.topk(cosine_scores, k=3)
                
                candidates = []
                for score, idx in zip(top_results[0], top_results[1]):
                    if score.item() >= SEMANTIC_THRESHOLD:
                        matched_slug = loader.semantic_keys[idx]
                        candidate_data = loader.semantic_dictionary[matched_slug].copy()
                        candidate_data["user_text"] = phrase
                        candidate_data["score"] = score.item()
                        candidate_data["is_negative"] = is_negative
                        candidates.append(candidate_data)
                
                if candidates:
                    if not hasattr(entities, 'semantic_matches'):
                        entities.semantic_matches = []
                    entities.semantic_matches.append(candidates)
                else:
                    # Fall back to testing individual words if the full phrase fails
                    words = phrase.split()
                    if len(words) > 1:
                        for word in words:
                            w_vector = loader.vector_model.encode(word, convert_to_tensor=True)
                            w_scores = util.cos_sim(w_vector, loader.semantic_tensors)[0]
                            w_top = torch.topk(w_scores, k=3)
                            
                            w_candidates = []
                            for w_score, w_idx in zip(w_top[0], w_top[1]):
                                if w_score.item() >= SEMANTIC_THRESHOLD:
                                    matched_slug = loader.semantic_keys[w_idx]
                                    candidate_data = loader.semantic_dictionary[matched_slug].copy()
                                    candidate_data["user_text"] = word
                                    candidate_data["score"] = w_score.item()
                                    candidate_data["is_negative"] = is_negative
                                    w_candidates.append(candidate_data)
                            
                            if w_candidates:
                                if not hasattr(entities, 'semantic_matches'):
                                    entities.semantic_matches = []
                                entities.semantic_matches.append(w_candidates)
                            else:
                                unmatched.append(word)
                    else:
                        unmatched.append(phrase)
                        
                return unmatched

            if cleaned_pos_text:
                still_unmatched_pos.extend(_process_vectors(cleaned_pos_text, is_negative=False))
            if cleaned_neg_text:
                still_unmatched_neg.extend(_process_vectors(cleaned_neg_text, is_negative=True))
    else:
        if cleaned_pos_text: still_unmatched_pos.append(cleaned_pos_text)
        if cleaned_neg_text: still_unmatched_neg.append(cleaned_neg_text)

    # Rejoin whatever survived both the Stop Words AND the Semantic AI
    if still_unmatched_pos:
        entities.search_term = " ".join(still_unmatched_pos)
    else:
        # Prevent STOP_WORDS from being resurrected via strict_search_term fallback
        fallback = _clean_leftovers(strict_search_term)
        entities.search_term = fallback if fallback else None

    entities.excluded_search_term = " ".join(still_unmatched_neg) if still_unmatched_neg else None
    
    # Auto-Materialize High-Confidence Matches & Bypass UI Interceptor
    if hasattr(entities, 'semantic_matches') and entities.semantic_matches:
        AUTO_APPLY_THRESHOLD = 0.85
        surviving_matches = []
        
        for candidates in entities.semantic_matches:
            if not candidates: continue
            best = max(candidates, key=lambda c: c.get("score", 0))
            
            if best.get("score", 0) >= AUTO_APPLY_THRESHOLD:
                match_type = best.get("type")
                slug = best.get("slug")
                
                if match_type == "category" and slug and not entities.target_category_slugs:
                    entities.target_category_slugs.add(slug)
                    entities.category_name = best.get("suggested_name", slug)
                elif match_type == "tag" and slug and slug not in entities.tag_slugs:
                    entities.tag_slugs.append(slug)
                    l = get_store_loader()
                    if l:
                        tag = l.tag_by_slug.get(slug)
                        if tag: entities.tag_ids.append(tag["id"])
                elif match_type == "attribute" and slug:
                    taxonomy = best.get("taxonomy", "")
                    if taxonomy and taxonomy not in entities.attributes:
                        entities.attributes[taxonomy] = slug
                        
                # Nullify search term since we mapped it to taxonomy
                entities.search_term = None 
            else:
                # Keep low-confidence matches for UI Clarification
                surviving_matches.append(candidates)
        
        # Overwrite so UI only intercepts weak matches
        entities.semantic_matches = surviving_matches

    # ─── SAFETY LOCK: RESTORING CORRECTNESS ───
    resolved_intent = original_nlp_result.intent
    final_confidence = original_nlp_result.confidence

    catalog_intent_values = {
        "filter_by_attribute", 
        "product_search", 
        "product_variations",
        "product_by_category",
        "product_by_tag",
        "product_by_attribute",
        "catalog_search",
        "category_browse",         
        "product_by_collection",   
        "product_list"             
    }

    # Protect action intents from being downgraded
    ACTION_INTENTS = {
        "place_order", "quick_order", "order_item",
        "product_variations", "product_detail", "product_attribute_info"
    }

    if resolved_intent.value in ACTION_INTENTS:
        pass  # Keep intact — these are deliberate user actions
    elif resolved_intent.value in catalog_intent_values or entities.product_id:
        resolved_intent = Intent.PRODUCT_SEARCH if entities.product_id else Intent.FILTER_BY_ATTRIBUTE
        final_confidence = max(final_confidence, 0.95)
    
    return ClassifiedResult(intent=resolved_intent, entities=entities, confidence=final_confidence)

# ══════════════════════════════════════════════════════════════
# ─── MAIN CHAT PIPELINE ───
# ══════════════════════════════════════════════════════════════

@chat_bp.route("/chat", methods=["POST"])
def chat():
    start_time = time.time()

    body = request.get_json(silent=True)
    if not body:
        logger.warning("POST /chat | Invalid JSON body")
        return jsonify({
            "success": False,
            "bot_message": "Invalid request. Send JSON with 'message' field.",
            "intent": "error",
            "products": [],
            "suggestions": ["Show me all products", "What categories do you have?"],
            "session_id": "",
            "metadata": {"error": "Invalid JSON body"},
            "pagination": default_pagination(),
        }), 400

    message = body.get("message", "").strip()
    page = int(body.get("page", 1))

    # ─── Language Detection & Translation ───────────────────────────────────
    # Detect if the message is Spanish (or another supported language) and
    # translate it to English before passing it through the rest of the pipeline.
    message, was_translated, detected_lang = detect_and_translate(message)
    if was_translated:
        logger.info(
            f"[LangCheck] Message translated from '{detected_lang}' to English | "
            f"translated='{message[:100]}'"
        )

    # 1. Resolve Sessions and Setup DB
    session_id = resolve_session_id()

    conversation = Conversation.query.get(session_id)
    if not conversation:
        conversation = Conversation(id=session_id)
        db.session.add(conversation)
        db.session.commit()

    # Capture customer ID from payload if provided
    payload_context = body.get("user_context", {})
    if payload_context.get("customer_id") and not conversation.customer_id:
        conversation.customer_id = payload_context.get("customer_id")
        db.session.commit()
        
    customer_id = conversation.customer_id
    user_context = conversation.context_data or {}
    
    # ── DEBUG LOG 1: Check the starting state ──
    logger.info(f"[MEMORY TRACE 1] INCOMING from Frontend Payload: {payload_context}")
    logger.info(f"[MEMORY TRACE 2] LOADED from Postgres DB: {user_context}")

    if user_context is not conversation.context_data:
        conversation.context_data = user_context

    truncated_msg = message[:100] + "..." if len(message) > 100 else message
    logger.info(f'POST /chat | session={session_id} | message="{sanitize_log_string(truncated_msg)}" | customer_id={customer_id} | flow_state={conversation.flow_state}')

    if not message:
        return jsonify({
            "success": False,
            "bot_message": "Please type a message! Try asking about our products, categories, or your orders.",
            "intent": "error",
            "products": [],
            "suggestions": ["Show me all products", "What categories do you have?"],
            "session_id": str(conversation.id),
            "metadata": {"error": "Empty message"},
            "pagination": default_pagination(page),
        }), 400

    try:
        # 2. OPTIMISTIC WRITE: Save User Message
        user_msg = Message(conversation_id=conversation.id, role="user", content=message)
        db.session.add(user_msg)
        db.session.commit()

        # Mock sessions dict to prevent existing handlers from crashing
        mock_sessions = {str(session_id): {"history": [], "user_context": user_context}}
        
        # ─── Step 0: Check conversation flow state ───
        try:
            current_flow_state = FlowState(conversation.flow_state)
        except ValueError:
            current_flow_state = FlowState.IDLE

        # ─── WIPE STALE CART DATA ON NEW CONVERSATIONS ───
        if current_flow_state in (FlowState.IDLE, FlowState.AWAITING_ANYTHING_ELSE):
            _keys_to_wipe = [
                "pending_product_id", "pending_product_name", 
                "pending_quantity", "pending_variation_id", "resolved_attributes"
            ]
            _wiped = False
            for k in _keys_to_wipe:
                if k in user_context:
                    user_context.pop(k)
                    _wiped = True
            
            if _wiped:
                conversation.context_data = user_context
                flag_modified(conversation, "context_data")
        # ─────────────────────────────────────────────────

        # ─── Step 0.5: Suggestion retry intercept ───
        _suggestion_retry = body.get("suggestion_retry")
        if _suggestion_retry:
            from store_registry import get_store_loader as _get_loader

            _sr_label = _suggestion_retry.get("label", "suggestion retry")
            _loader = _get_loader()
            _sr_entities = ExtractedEntities()

            _cat_slug = _suggestion_retry.get("category_slug", "")
            if _cat_slug and _loader:
                _cat_entry = _loader.category_by_slug.get(_cat_slug)
                if _cat_entry:
                    _sr_entities.category_name = _cat_entry["name"]
                    _sr_entities.category_id = _cat_entry["id"]

            for _extra_slug in (_suggestion_retry.get("extra_category_slugs") or []):
                if _loader:
                    _extra_entry = _loader.category_by_slug.get(_extra_slug)
                    if _extra_entry:
                        _sr_entities.extra_category_ids.append(_extra_entry["id"])

            for _tslug in (_suggestion_retry.get("tag_slugs") or []):
                _sr_entities.tag_slugs.append(_tslug)
                if _loader:
                    _tid = _loader.get_tag_id_by_slug(_tslug)
                    if _tid:
                        _sr_entities.tag_ids.append(_tid)

            _sr_entities.attributes = dict(_suggestion_retry.get("attributes") or {})

            _sr_intent = Intent.FILTER_BY_ATTRIBUTE
            _sr_confidence = 1.0
            _sr_result = ClassifiedResult(intent=_sr_intent, entities=_sr_entities, confidence=_sr_confidence)

            _sr_api_calls = build_api_calls(_sr_result, page, user_message=message, session_id=session_id, customer_id=customer_id)

            if customer_id:
                _resolve_user_placeholders(_sr_api_calls, customer_id)

            _sr_responses = woo_client.execute_all(_sr_api_calls)
            _sr_products_raw = []
            for _r in _sr_responses:
                if _r.get("success"):
                    _d = _r.get("data")
                    if isinstance(_d, dict) and "products" in _d: _sr_products_raw.extend(_d["products"])
                    elif isinstance(_d, list): _sr_products_raw.extend(_d)
                    elif isinstance(_d, dict): _sr_products_raw.append(_d)

            _sr_formatted = []
            for _p in _sr_products_raw:
                if _p.get("parent_id"): continue
                if "featured_image" in _p: _sr_formatted.append(format_custom_product(_p))
                else: _sr_formatted.append(format_product(_p))
            _sr_formatted = [p for p in _sr_formatted if p.get("name")]

            _sr_bot_message = f"Here are results for **{_sr_label}**:" if _sr_formatted else f"No products found for **{_sr_label}** either. Try a different filter."
            _sr_pagination = build_pagination(page, _sr_responses, _sr_api_calls)
            elapsed = time.time() - start_time

            return _finalize_turn(conversation, jsonify({
                "success": True,
                "bot_message": _sr_bot_message,
                "intent": "filter",
                "products": _sr_formatted,
                "suggestions": [],
                "filter_suggestions": [],
                "session_id": str(conversation.id),
                "metadata": {
                    "confidence": 1.0,
                    "products_count": len(_sr_formatted),
                    "provider": CLASSIFIER_PROVIDER_TAG,
                    "response_time_ms": round(elapsed * 1000),
                    "intent_raw": "suggestion_retry",
                },
                "pagination": _sr_pagination,
                "flow_state": FlowState.IDLE.value,
            }))

        # ─── Step 0: Check conversation flow state ───
        try:
            current_flow_state = FlowState(conversation.flow_state)
        except ValueError:
            current_flow_state = FlowState.IDLE

        _skip_classification = False
        bypass_result = None

        if current_flow_state == FlowState.AWAITING_FILTER_CLARIFICATION:
            pending_semantic = user_context.get("pending_semantic_match")
            if pending_semantic:
                
                msg_lower = message.lower().strip()
                
                # Check if the exact suggestion name is contained anywhere in the message
                is_accept = False
                selected_match = None
                
                if "options" in pending_semantic:
                    for opt in pending_semantic["options"]:
                        if opt["suggested_name"].lower() in msg_lower:
                            is_accept = True
                            selected_match = opt
                            break
                
                # Fallback to the existing strict prefix checks
                if not is_accept and (
                    msg_lower == "yes - use these filters" 
                    or msg_lower.startswith("yes - use ") 
                    or msg_lower.startswith("yes - exclude ") 
                    or msg_lower.startswith("use ")
                    or msg_lower.startswith("exclude ")
                    or msg_lower in ["yes", "y", "yep", "sure", "ok"]
                ):
                    is_accept = True
                    if "options" in pending_semantic:
                        selected_match = pending_semantic["options"][0]

                is_reject = msg_lower.startswith("no - ") or msg_lower in ["no", "n", "nope"]
                is_cancel = msg_lower in ["cancel", "exit", "stop", "nevermind", "never mind", "abort", "start over"]
                
                if is_cancel:
                    user_context.pop("pending_semantic_match", None)
                    
                is_skip = msg_lower in ["skip - use my current filters", "skip"]

                if is_accept or is_reject or is_skip:
                    entities = ExtractedEntities()
                    entities.target_category_slugs = set()
                    
                    if is_accept:
                        options_to_apply = []
                        if selected_match:
                            options_to_apply.append(selected_match)
                        elif "options" in pending_semantic:
                            options_to_apply.extend(pending_semantic["options"])
                                
                        options_to_apply.extend(pending_semantic.get("extra_semantics", []))
                        
                        for opt in options_to_apply:
                            is_neg = opt.get("is_negative", False)
                            if opt["type"] == "tag":
                                if is_neg:
                                    if not hasattr(entities, 'excluded_tags'): entities.excluded_tags = []
                                    entities.excluded_tags.append(opt["slug"])
                                else:
                                    entities.tag_slugs.append(opt["slug"])
                            elif opt["type"] == "category":
                                if is_neg:
                                    if not hasattr(entities, 'excluded_categories'): entities.excluded_categories = []
                                    entities.excluded_categories.append(opt["slug"])
                                else:
                                    entities.target_category_slugs.add(opt["slug"])
                                    entities.category_name = opt["suggested_name"]
                            elif opt["type"] == "attribute":
                                taxonomy = opt["taxonomy"]
                                if is_neg:
                                    if not hasattr(entities, 'excluded_attributes'): entities.excluded_attributes = {}
                                    if taxonomy not in entities.excluded_attributes: entities.excluded_attributes[taxonomy] = []
                                    entities.excluded_attributes[taxonomy].append(opt["slug"])
                                else:
                                    if taxonomy not in entities.attributes: entities.attributes[taxonomy] = opt["slug"]
                                    else:
                                        if opt["slug"] not in entities.attributes[taxonomy].split(","): entities.attributes[taxonomy] += f",{opt['slug']}"

                    elif is_reject:
                        if "rejected_semantic_terms" not in user_context: user_context["rejected_semantic_terms"] = []
                        for opt in pending_semantic.get("options", []):
                            user_context["rejected_semantic_terms"].append(opt["suggested_name"])

                    # is_skip: no action here — carryovers below do all the work

                    leftovers = pending_semantic.get("pending_other_semantics", [])
                    if leftovers: entities.semantic_matches.extend(leftovers)

                    # ── Carryover Restore ──
                    if pending_semantic.get("carryover_tags"): entities.tag_slugs.extend(pending_semantic["carryover_tags"])
                    if pending_semantic.get("carryover_categories"): entities.target_category_slugs.update(pending_semantic["carryover_categories"])
                    if pending_semantic.get("carryover_category_name"): entities.category_name = pending_semantic["carryover_category_name"]
                    if pending_semantic.get("carryover_product_id"): entities.product_id = pending_semantic["carryover_product_id"]
                    if pending_semantic.get("carryover_product_name"): entities.product_name = pending_semantic["carryover_product_name"]
                    if pending_semantic.get("carryover_quantity") is not None: entities.quantity = pending_semantic["carryover_quantity"]
                    if pending_semantic.get("carryover_order_id") is not None: entities.order_id = pending_semantic["carryover_order_id"]
                    if pending_semantic.get("carryover_collection_year") is not None: entities.collection_year = pending_semantic["carryover_collection_year"]
                    if pending_semantic.get("carryover_in_stock") is not None: entities.in_stock = pending_semantic["carryover_in_stock"]
                    if pending_semantic.get("carryover_on_sale") is not None: entities.on_sale = pending_semantic["carryover_on_sale"]
                    if pending_semantic.get("carryover_min_price") is not None: entities.min_price = pending_semantic["carryover_min_price"]
                    if pending_semantic.get("carryover_max_price") is not None: entities.max_price = pending_semantic["carryover_max_price"]
                        
                    if pending_semantic.get("carryover_attributes"):
                        for k, v in pending_semantic["carryover_attributes"].items():
                            if k not in entities.attributes: entities.attributes[k] = v
                            else:
                                if v not in entities.attributes[k].split(","): entities.attributes[k] += f",{v}"
                                
                    if pending_semantic.get("carryover_excluded_tags"):
                        if not hasattr(entities, 'excluded_tags'): entities.excluded_tags = []
                        entities.excluded_tags.extend(pending_semantic["carryover_excluded_tags"])
                    if pending_semantic.get("carryover_excluded_categories"):
                        if not hasattr(entities, 'excluded_categories'): entities.excluded_categories = []
                        entities.excluded_categories.extend(pending_semantic["carryover_excluded_categories"])
                    if pending_semantic.get("carryover_excluded_attributes"):
                        if not hasattr(entities, 'excluded_attributes'): entities.excluded_attributes = {}
                        for k, v in pending_semantic["carryover_excluded_attributes"].items():
                            if k not in entities.excluded_attributes: entities.excluded_attributes[k] = v
                            else: entities.excluded_attributes[k].extend(v)

                    # Restore OR pairs (added in previous session)
                    if pending_semantic.get("carryover_attr_tag_or_pairs"):
                        if not hasattr(entities, 'attr_tag_or_pairs'): entities.attr_tag_or_pairs = []
                        entities.attr_tag_or_pairs.extend(pending_semantic["carryover_attr_tag_or_pairs"])

                    # search_term assignment moved here so carryover_search_term doesn't silently overwrite is_reject / is_skip intent
                    if is_reject:
                        entities.search_term = pending_semantic.get("options", [{}])[0].get("user_text", "")
                    elif is_skip:
                        entities.search_term = None
                    else:
                        # is_accept: only restore search_term if nothing was matched
                        if pending_semantic.get("carryover_search_term"):
                            entities.search_term = pending_semantic["carryover_search_term"]

                    current_flow_state = FlowState.IDLE
                    user_context["flow_state"] = FlowState.IDLE.value
                    user_context.pop("pending_semantic_match", None)
                    
                    conversation.context_data = user_context
                    
                    bypass_intent = Intent.PRODUCT_SEARCH if getattr(entities, 'product_id', None) else Intent.FILTER_BY_ATTRIBUTE
                    bypass_result = ClassifiedResult(intent=bypass_intent, entities=entities, confidence=0.98)
                    _skip_classification = True

        flow_context = {
            "pending_product_name": user_context.get("pending_product_name"),
            "pending_product_id": user_context.get("pending_product_id"),
            "pending_quantity": user_context.get("pending_quantity"),
            "pending_variation_id": user_context.get("pending_variation_id"),
            "resolved_attributes": user_context.get("resolved_attributes"),
        }
        
        flow_result = None
        if current_flow_state != FlowState.IDLE:
            flow_result = handle_flow_state(
                state=current_flow_state,
                message=message,
                entities=flow_context,
                confidence=0.0,
            )
            if flow_result and flow_result.get("override_message"):
                message = flow_result["override_message"]
                
        if flow_result:
            _persistent_keys = [
                "pending_product_id", "pending_product_name", "pending_quantity", 
                "pending_variation_id", "pending_shipping_address", 
                "use_existing_address", "use_new_address", "resolved_attributes"
            ]
            for k in _persistent_keys:
                if k in flow_result and flow_result[k] is not None:
                    user_context[k] = flow_result[k]
                    
            # Plug the updated clone back into the ORM!
            conversation.context_data = user_context
            flag_modified(conversation, "context_data")
            
            logger.info(f"[MEMORY TRACE 3] STATE MACHINE returned: {flow_result}")
            logger.info(f"[MEMORY TRACE 4] UPDATED user_context before handlers: {user_context}")

        if flow_result and not flow_result.get("pass_through") and not flow_result.get("override_message"):
            resp = handle_flow(flow_result, user_context, str(conversation.id), customer_id, page, start_time, mock_sessions)
            if resp: return _finalize_turn(conversation, resp)

        elif flow_result:
            resp = handle_flow(flow_result, user_context, str(conversation.id), customer_id, page, start_time, mock_sessions)
            if resp: return _finalize_turn(conversation, resp)

        _resolve_variant = bool(flow_result and flow_result.get("resolve_variant"))
        
        if _skip_classification:
            result = bypass_result
            intent = result.intent
            entities = result.entities
            confidence = result.confidence
            
        else:
            store_loader = get_store_loader()
            result = parse_csv_message(message, store_loader)
            if not result:
                result = classify(message)

            intent = result.intent
            entities = result.entities
            confidence = result.confidence

        # LOCK IN VARIANT STATE: Intercept after NLP extracts attributes, but before LLM
        if current_flow_state == FlowState.AWAITING_VARIANT_SELECTION:
            _resolve_variant = True
            intent = Intent.QUICK_ORDER
            result.intent = intent
            entities.product_id = user_context.get("pending_product_id")
            entities.product_name = user_context.get("pending_product_name")
            confidence = 1.0

        # Setup minimal session history for LLM
        session_history = [{"role": m.role, "message": m.content} for m in conversation.messages[-4:-1]]

        # Skip LLM fallback if we just forced the variant selection intent
        if not _resolve_variant:
            llm_outcome = run_llm_fallback(
                message=message,
                intent=intent,
                entities=entities,
                confidence=confidence,
                session_id=str(conversation.id),
                session_history=session_history,
                store_loader=store_loader,
                page=page,
                start_time=start_time,
                order_create_intents=ORDER_CREATE_INTENTS,
                user_context=user_context,
                sessions=mock_sessions,
            )

            if llm_outcome is not None:
                if not isinstance(llm_outcome, tuple) or not isinstance(llm_outcome[0], tuple):
                    if hasattr(llm_outcome, 'get_data'):  
                        return _finalize_turn(conversation, llm_outcome)
                    if isinstance(llm_outcome, tuple) and len(llm_outcome) == 2 and isinstance(llm_outcome[1], int):
                        return _finalize_turn(conversation, llm_outcome)
                if isinstance(llm_outcome, tuple) and len(llm_outcome) == 4:
                    intent, entities, confidence, result = llm_outcome        
        if entities.semantic_matches and current_flow_state != FlowState.AWAITING_FILTER_CLARIFICATION and intent not in (Intent.PRODUCT_ATTRIBUTE_INFO, Intent.PRODUCT_VARIATIONS):
            rejected_list = user_context.get("rejected_semantic_terms", [])
            valid_term_groups = []
            
            for candidate_list in entities.semantic_matches:
                if isinstance(candidate_list, dict): candidate_list = [candidate_list]
                clean_list = [c for c in candidate_list if c["suggested_name"] not in rejected_list]
                if clean_list: valid_term_groups.append(clean_list)
                    
            reject_flow = flow_result and flow_result.get("reject_semantic_match")
            
            if valid_term_groups and not reject_flow:
                has_ties = any(len(group) > 1 for group in valid_term_groups)
                stashed_semantic_data = {
                    "carryover_search_term": entities.search_term,
                    "carryover_tags": list(entities.tag_slugs),
                    "carryover_attributes": entities.attributes,
                    "carryover_excluded_tags": getattr(entities, 'excluded_tags', []),
                    "carryover_excluded_categories": getattr(entities, 'excluded_categories', []),
                    "carryover_excluded_attributes": getattr(entities, 'excluded_attributes', {}),
                    "carryover_product_id": entities.product_id,
                    "carryover_product_name": entities.product_name,
                    "carryover_quantity": getattr(entities, 'quantity', None),
                    "carryover_order_id": getattr(entities, 'order_id', None),
                    "carryover_collection_year": getattr(entities, 'collection_year', None),
                    "carryover_in_stock": getattr(entities, 'in_stock', None),
                    "carryover_on_sale": getattr(entities, 'on_sale', None),
                    "carryover_min_price": getattr(entities, 'min_price', None),
                    "carryover_max_price": getattr(entities, 'max_price', None),
                    "carryover_attr_tag_or_pairs": list(getattr(entities, 'attr_tag_or_pairs', [])),
                    "carryover_categories": list(getattr(entities, 'target_category_slugs', set())),
                    "carryover_category_name": getattr(entities, 'category_name', None),            
                }
                
                has_strong_filters = bool(
                    entities.target_category_slugs or
                    entities.tag_slugs or
                    entities.attributes or
                    getattr(entities, 'attr_tag_or_pairs', [])
                )

                suggestion_buttons = []
                if has_ties:
                    active_group = valid_term_groups[0]
                    user_original_term = active_group[0]["user_text"]
                    is_negative = active_group[0].get("is_negative", False)
                    
                    stashed_semantic_data["options"] = active_group
                    stashed_semantic_data["pending_other_semantics"] = valid_term_groups[1:]
                    
                    action_word = "EXCLUDE" if is_negative else "USE"
                    bot_message = f"I found multiple matches for '{user_original_term}'. Which one did you mean to {action_word}?"
                    for candidate in active_group:
                        verb = "Exclude" if candidate.get("is_negative") else "Use"
                        suggestion_buttons.append(f"{verb} {candidate['suggested_name']}")
                    suggestion_buttons.append(f"No - search for '{user_original_term}'")
                    if has_strong_filters:
                        suggestion_buttons.append("Skip - use my current filters")

                else:
                    primary_semantics = [group[0] for group in valid_term_groups]
                    stashed_semantic_data["options"] = [primary_semantics[0]]
                    stashed_semantic_data["extra_semantics"] = primary_semantics[1:]
                    
                    suggested_names = [f["suggested_name"] for f in primary_semantics]
                    is_negative = primary_semantics[0].get("is_negative", False)
                    
                    if len(suggested_names) == 1:
                        if is_negative:
                            bot_message = f"I don't have an exact match for '{primary_semantics[0]['user_text']}'. Did you mean to **EXCLUDE** {suggested_names[0]}?"
                            suggestion_buttons.append(f"Yes - exclude {suggested_names[0]}")
                        else:
                            bot_message = f"I don't have an exact match for '{primary_semantics[0]['user_text']}', but I do have **{suggested_names[0]}**. Would you like to use that filter?"
                            suggestion_buttons.append(f"Yes - use {suggested_names[0]}")
                        suggestion_buttons.append(f"No - search for '{primary_semantics[0]['user_text']}'")
                        if has_strong_filters:
                            suggestion_buttons.append("Skip - use my current filters")
                    else:
                        joined_names = " and ".join(suggested_names)
                        bot_message = f"I don't have exact matches, but I found **{joined_names}**. Would you like to apply these filters?"
                        suggestion_buttons.append("Yes - use these filters")
                        suggestion_buttons.append("No - use my original text")
                        if has_strong_filters:
                            suggestion_buttons.append("Skip - use my current filters")

                suggestion_buttons.append("Cancel")
                
                elapsed = time.time() - start_time
                user_context["pending_semantic_match"] = stashed_semantic_data
                
                # Explicitly re-attach the mutated dictionary to the refreshed ORM object
                conversation.context_data = user_context 
                flag_modified(conversation, "context_data")
                
                return _finalize_turn(conversation, jsonify({
                    "success": True,
                    "bot_message": bot_message,
                    "intent": "guided_flow",
                    "products": [],
                    "suggestions": suggestion_buttons,
                    "session_id": str(conversation.id),
                    "metadata": {
                        "flow_state": FlowState.AWAITING_FILTER_CLARIFICATION.value,
                        "pending_semantic_match": stashed_semantic_data,
                        "response_time_ms": round(elapsed * 1000),
                    },
                    "flow_state": FlowState.AWAITING_FILTER_CLARIFICATION.value,
                    "pagination": default_pagination(page),
                }))
        # ── Guardrail: catch empty order intents before wasting an API call ──
        _is_empty_order = False
        if intent in ORDER_CREATE_INTENTS and not getattr(entities, 'product_id', None):
            _p_name = (getattr(entities, 'product_name', None) or "").lower().strip()
            _s_term = (getattr(entities, 'search_term', None) or "").lower().strip()
            
            # Catch generic filler words that the NLP might accidentally extract
            _generic_words = {"", "product", "a product", "the product", "item", "an item", "something", "anything", "order", "some"}
            
            if _p_name in _generic_words and _s_term in _generic_words and not getattr(entities, 'attributes', {}) and not getattr(entities, 'target_category_slugs', set()):
                _is_empty_order = True
                logger.info(f"🛑 Caught generic words, stopping API call | p_name='{_p_name}' | s_term='{_s_term}'")
            else:
                logger.debug(f"✅ Valid order intent | p_name='{_p_name}' | s_term='{_s_term}'")

        if _is_empty_order:
            elapsed = time.time() - start_time
            return _finalize_turn(conversation, jsonify({
                "success": True,
                "bot_message": "To place an order, please include the product name! For example, you can type: **'I want to order Plumeria'**.",
                "intent": "clarification_needed",
                "products": [],
                "suggestions": ["Show me the catalog", "Cancel"],
                "session_id": str(conversation.id),
                "metadata": {
                    "confidence": 1.0,
                    "products_count": 0,
                    "response_time_ms": round(elapsed * 1000),
                },
                "pagination": default_pagination(page),
                "flow_state": FlowState.IDLE.value,
            }))
            
        api_calls = build_api_calls(result, page, user_message=message, session_id=str(conversation.id), customer_id=customer_id)

        if customer_id:
            _resolve_user_placeholders(api_calls, customer_id)

        last_product_ctx = user_context.get("last_product")
        all_products_raw = []
        order_data = []
        api_responses = []
        api_calls_to_execute = []
           
        if not _resolve_variant:
            filtered_api_calls = []
            if intent in ORDER_CREATE_INTENTS:
                for call in api_calls:
                    if call.method == "POST" and "/orders" in call.endpoint: continue
                    filtered_api_calls.append(call)
                api_calls_to_execute = filtered_api_calls
            else:
                api_calls_to_execute = api_calls

            api_responses = woo_client.execute_all(api_calls_to_execute)

            def _enrich_raw_products(prod_list):
                for p in prod_list:
                    if "type" not in p: p["type"] = "variable" if p.get("variations") else "simple"

            for resp in api_responses:
                if resp.get("success"):
                    data = resp.get("data")
                    if isinstance(data, dict) and "products" in data:
                        _enrich_raw_products(data["products"])
                        (order_data if intent in ORDER_INTENTS else all_products_raw).extend(data["products"])
                    elif isinstance(data, list):
                        _enrich_raw_products(data)
                        (order_data if intent in ORDER_INTENTS else all_products_raw).extend(data)
                    elif isinstance(data, dict):
                        _enrich_raw_products([data])
                        (order_data if intent in ORDER_INTENTS else all_products_raw).append(data)

            log_matched_products(all_products_raw, api_calls_to_execute)

            # Save last product to memory for next-turn pronoun/variant resolution
            if all_products_raw and not _resolve_variant:
                first_prod = all_products_raw[0]
                user_context["last_product"] = {"id": first_prod.get("id"), "name": first_prod.get("name")}
                if current_flow_state != FlowState.AWAITING_VARIANT_SELECTION:
                    user_context["pending_product_id"] = first_prod.get("id")
                    user_context["pending_product_name"] = first_prod.get("name")
                    conversation.context_data = user_context
                    flag_modified(conversation, "context_data")
        
        if intent == Intent.FETCH_CUSTOMER:
            elapsed = int((time.time() - start_time) * 1000)
            customer_raw = order_data[0] if order_data else {}
            
            display = {}
            for field_key in entities.customer_fields_requested:
                if "." in field_key:
                    section, key = field_key.split(".", 1)
                    display[field_key] = customer_raw.get(section, {}).get(key)
                elif field_key == "full_name":
                    display["name"] = f"{customer_raw.get('first_name', '')} {customer_raw.get('last_name', '')}".strip()
                else:
                    display[field_key] = customer_raw.get(field_key)
            
            lines = [f"**{k}**: {v or 'not set'}" for k, v in display.items()]
            
            return _finalize_turn(conversation, jsonify({
                "success": True,
                "bot_message": "Here's what I have on file:\n" + "\n".join(lines),
                "intent": "fetch_customer",
                "products": [],
                "suggestions": [],
                "session_id": str(conversation.id),
                "metadata": {"confidence": round(confidence, 2), "response_time_ms": elapsed},
                "pagination": default_pagination(page),
                "flow_state": FlowState.IDLE.value,
            }))

        if intent == Intent.UPDATE_CUSTOMER:
            elapsed = int((time.time() - start_time) * 1000)
            update_success = False
            for _api_call, _api_resp in zip(api_calls_to_execute, api_responses):
                if _api_call.method == "PUT" and "/customers/" in _api_call.endpoint:
                    update_success = _api_resp.get("success", False)
                    break
            _update_signal = [{"success": update_success}]
            
            return _finalize_turn(conversation, jsonify({
                "success":     update_success,
                "bot_message": generate_bot_message(intent, entities, [], confidence, _update_signal),
                "intent":      intent.value,
                "products":    [],
                "suggestions": generate_suggestions(intent, entities, []),
                "session_id":  str(conversation.id),
                "metadata": {
                    "confidence": round(confidence, 2),
                    "products_count": 0,
                    "provider": CLASSIFIER_PROVIDER_TAG,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "response_time_ms": elapsed,
                    "intent_raw": intent.value,
                    "entities": _entities_to_dict(entities),
                },
                "pagination":  default_pagination(page),
                "flow_state":  FlowState.IDLE.value,
            }))

        # Route through Handlers
        resp = handle_reorder(intent, entities, order_data, customer_id, str(conversation.id), page, start_time, mock_sessions)
        if resp: return _finalize_turn(conversation, resp)

        resp = handle_order_detail(current_flow_state, customer_id, user_context, str(conversation.id), page, start_time)
        if resp: return _finalize_turn(conversation, resp)
        
        resp = handle_historical_search(intent, entities, order_data, customer_id, str(conversation.id), page, start_time, mock_sessions)
        if resp: return _finalize_turn(conversation, resp)

        resp = handle_variant_selection(current_flow_state, intent, entities, message, customer_id, str(conversation.id), page, start_time, mock_sessions, user_context, _resolve_variant)
        if resp: return _finalize_turn(conversation, resp)
        
        resp = handle_quantity_and_variant_check(intent, entities, all_products_raw, order_data, ORDER_CREATE_INTENTS, str(conversation.id), page, start_time, mock_sessions, customer_id=customer_id)
        if resp: return _finalize_turn(conversation, resp)

        resp = handle_quick_order(intent, entities, all_products_raw, last_product_ctx, customer_id, str(conversation.id), page, start_time, mock_sessions, ORDER_CREATE_INTENTS)
        if resp:
            # Save pending_product_id before early exit so Turn 2 can find it
            if getattr(entities, 'product_id', None):
                user_context["pending_product_id"] = entities.product_id
                user_context["pending_product_name"] = getattr(entities, 'product_name', None)
                conversation.context_data = user_context
                flag_modified(conversation, "context_data")
            return _finalize_turn(conversation, resp)

        resp = handle_variation_product(intent, entities, api_responses, api_calls_to_execute, confidence, order_data, str(conversation.id), page, start_time, mock_sessions)
        if resp: return _finalize_turn(conversation, resp)

        store_loader = get_store_loader()
        all_products_raw, resp = handle_empty_results(intent, entities, all_products_raw, message, str(conversation.id), page, start_time, confidence, mock_sessions, store_loader)
        if resp: return _finalize_turn(conversation, resp)

        # Final Formatting
        products = []
        categories = []
        suggestions_list=[]
        
        if intent in (Intent.CATEGORY_LIST, Intent.PRODUCT_CATALOG):
            seen_names = set()
            for cat in all_products_raw:
                name = cat.get("name", "")
                if name and name not in seen_names:
                    seen_names.add(name)
                    categories.append({
                        "id": cat.get("id"),
                        "name": name.replace("&amp;", "&"),
                        "slug": cat.get("slug", ""),
                        "count": cat.get("count", 0)
                    })
        else:
            for p in all_products_raw:
                if p.get("parent_id"): continue
                if isinstance(p.get("attributes"), dict): products.append(format_custom_product(p))
                else: products.append(format_product(p))
        
        products = [p for p in products if p.get("name")]
        
        _pagination_data = build_pagination(page, api_responses, api_calls_to_execute)
        
        # CUSTOM CATALOG MESSAGE & SUGGESTIONS
        if intent in (Intent.CATEGORY_LIST, Intent.PRODUCT_CATALOG):
            bot_message = "Here are our top categories to help you get started!"
            suggestions_list = ["Cancel"]
        else:
            bot_message = generate_bot_message(
                intent, 
                entities, 
                products, 
                confidence, 
                order_data, 
                total_items=_pagination_data.get("total_items"),
                page=page 
            )
            suggestions_list = generate_suggestions(intent, entities, products)

        elapsed = time.time() - start_time
        response = {
            "success": True,
            "bot_message": bot_message,
            "intent": intent.value,
            "products": products,
            "categories": categories,
            "suggestions": suggestions_list,
            "session_id": str(conversation.id),
            "metadata": {
                "confidence": round(confidence, 2),
                "products_count": len(products),
                "categories_count": len(categories),
                "provider": CLASSIFIER_PROVIDER_TAG,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "response_time_ms": round(elapsed * 1000),
                "intent_raw": intent.value,
                "entities": _entities_to_dict(entities),
            },
            "pagination": _pagination_data,
        }
        
        if intent in (Intent.ORDER_HISTORY, Intent.LAST_ORDER) and order_data:
            response["orders"] = [format_order_for_frontend(o) for o in order_data]
            response["order_pagination"] = build_pagination(page, api_responses, api_calls_to_execute)

        response["flow_state"] = (
            FlowState.AWAITING_ANYTHING_ELSE.value
            if intent in ORDER_CREATE_INTENTS and order_data
            else FlowState.IDLE.value
        )

        return _finalize_turn(conversation, jsonify(response))

    except Exception as e:
        # ─── CRITICAL DB ROLLBACK ───
        db.session.rollback()
        logger.error(f"Pipeline Crash for session {session_id}: {str(e)}")

        error_msg = Message(
            conversation_id=conversation.id, 
            role="bot", 
            content="I encountered a system issue while processing that. Can you try again?",
            intent="error"
        )
        db.session.add(error_msg)
        db.session.commit()

        return jsonify({
            "success": False,
            "session_id": str(conversation.id),
            "intent": "error",
            "bot_message": error_msg.content,
            "products": [],
            "suggestions": ["Start over", "Show me all products"]
        }), 500