from typing import Protocol, Optional

from models import WooAPICall


class EcommerceEndpoints(Protocol):
    def fetch_product(self, product_id: int, *, description: str = "") -> WooAPICall: ...
    def list_products(self, *, page: int = 1, per_page: int = 20, search: Optional[str] = None,
                      on_sale: Optional[bool] = None, description: str = "",
                      requires_resolution: Optional[list[str]] = None) -> WooAPICall: ...
    def fetch_variant(self, product_id: int, variant_id: int, *, description: str = "") -> WooAPICall: ...
    def list_variants(self, product_id: int, *, page: int = 1, per_page: int = 100,
                      status: str = "publish", description: str = "") -> WooAPICall: ...
    def products_advanced(self, body: dict, *, description: str = "",
                          requires_resolution: Optional[list[str]] = None) -> WooAPICall: ...
    def fetch_order(self, order_id: int, *, description: str = "") -> WooAPICall: ...
    def list_customer_orders(self, *, customer_id: object, page: int = 1, per_page: int = 20,
                             after: Optional[str] = None, before: Optional[str] = None,
                             include: Optional[list[int]] = None, description: str = "",
                             requires_resolution: Optional[list[str]] = None) -> WooAPICall: ...
    def list_customer_orders_custom(self, body: dict, *, description: str = "",
                                    requires_resolution: Optional[list[str]] = None) -> WooAPICall: ...
    def create_order(self, payload: dict, *, description: str = "",
                     requires_resolution: Optional[list[str]] = None) -> WooAPICall: ...
    def fetch_customer(self, customer_id: int, *, description: str = "") -> WooAPICall: ...
    def update_customer(self, customer_id: int, payload: dict, *, description: str = "") -> WooAPICall: ...
    def list_categories(self, *, page: int = 1, per_page: int = 100, hide_empty: bool = True,
                        orderby: str = "name", order: str = "asc", description: str = "") -> WooAPICall: ...
    def list_tags(self, *, page: int = 1, per_page: int = 100, hide_empty: bool = True,
                  description: str = "") -> WooAPICall: ...
    def list_attribute_terms(self, attribute_id: int, *, per_page: int = 100,
                             description: str = "") -> WooAPICall: ...
    def list_coupons(self, *, page: int = 1, per_page: int = 20, description: str = "") -> WooAPICall: ...
    def fetch_wishlist(self, customer_id: object, *, description: str = "") -> WooAPICall: ...
