"""change customer_id to string

Revision ID: e5ef94059f68
Revises: 
Create Date: 2026-05-22 08:41:25.250691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ef94059f68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True,
               postgresql_using='customer_id::text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               postgresql_using='customer_id::integer')

    # ### end Alembic commands ###
